version: '3.8'

services:
  web:
    build:
      context: web/.
      dockerfile: Dockerfile 
    volumes:
      - /run/udev:/run/udev:ro
      - /var/run/docker.sock:/var/run/docker.sock # for using docker demon
    network_mode: "host"
    privileged: true
    container_name: web

  tflite:
    build:
      context: tflite/.
      dockerfile: Dockerfile 
    volumes:
      - /run/udev:/run/udev:ro
    privileged: true
    container_name: tflite
    network_mode: "host"
    
  onnx:
    build:
      context: onnx/.
      dockerfile: Dockerfile 
    volumes:
      - /run/udev:/run/udev:ro
    privileged: true
    container_name: onnx
    network_mode: "host"